system:
  name: "apsc_admin"
  host: "127.0.0.1"
  port: 8080
  mode: "development"
  secret: "apsc_admin"

database:
  driver: "mysql"
  host: "192.168.2.8"
  port: 3306
  dbname: "apsc_admin"
  username: "gan"
  password: "Ghj201711#"